// This file will be generated by `flutterfire configure`
// DO NOT edit manually - run the command mentioned in SETUP_FLUTTERFIRE.md

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web platform not configured yet. Run flutterfire configure.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'macOS not configured yet. Run flutterfire configure.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_TC1XICaQslzZm20TJi07kTIn9Odp0SA',
    appId: '1:486478193659:ios:dbc2e3ec971a141507e15e',
    messagingSenderId: '486478193659',
    projectId: 'quicktutor2',
    storageBucket: 'quicktutor2.appspot.com',
    iosBundleId: 'com.example.quicktutor2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF6Fr58DQ-bFfHwLcQb_iAyIi-JpYUKbA',
    appId: '1:486478193659:android:6a0d8e096cda2aef07e15e',
    messagingSenderId: '486478193659',
    projectId: 'quicktutor2',
    storageBucket: 'quicktutor2.appspot.com',
  );
}
